meta_product_name: "Decide for me"
meta_title: "Decide for me - collective decision making app"
meta_description: "If you have a question on a specific topic you can always ask for some help"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
